"""walldye: the Python API procedural SVG wallpapers are drawn with.

A design is wallpapers/<slug>/design.py: module-level constants, a Params subclass and one
`@design(...) def draw(s: Canvas[P]) -> None`. Colours are symbolic theme formulas; the tools
draw each (variant, aspect, regime) once into a document and serialise it under every theme.
The helpers live in walldye.geom, walldye.field and walldye.pixel; docs/api.md is the reference.
"""

from ._canvas import (
    Buckets,
    Canvas,
    ClipSurface,
    FillRule,
    LineCap,
    LineJoin,
    MaskPaint,
    MaskStop,
    MaskSurface,
    NpRng,
    Paint,
    PatternSurface,
    Ref,
    Rng,
    Stop,
    Style,
)
from ._colour import (
    ACCENT,
    ACCENT_1,
    ACCENT_2,
    ACCENT_3,
    ACCENT_4,
    ACCENT_5,
    ACCENT_6,
    ACCENT_7,
    ACCENT_8,
    ACCENT_HI,
    BG,
    BG_ALT,
    BG_DEEP,
    BLACK,
    FG,
    FG_ALT,
    MASK_BLACK,
    MASK_WHITE,
    MUTED,
    UI,
    UI_ALT,
    UI_HI,
    Colour,
    Ladder,
    MaskColour,
    by_regime,
    ladder,
    mix,
    ramp,
)
from ._design import design
from ._params import Params, knob
from ._path import P, Path
from ._vec import Num, Point, Rect, Vec, clamp, lerp, polar, smoothstep

__all__ = [
    "ACCENT",
    "ACCENT_1",
    "ACCENT_2",
    "ACCENT_3",
    "ACCENT_4",
    "ACCENT_5",
    "ACCENT_6",
    "ACCENT_7",
    "ACCENT_8",
    "ACCENT_HI",
    "BG",
    "BG_ALT",
    "BG_DEEP",
    "BLACK",
    "FG",
    "FG_ALT",
    "MASK_BLACK",
    "MASK_WHITE",
    "MUTED",
    "UI",
    "UI_ALT",
    "UI_HI",
    "Buckets",
    "Canvas",
    "ClipSurface",
    "Colour",
    "FillRule",
    "Ladder",
    "LineCap",
    "LineJoin",
    "MaskColour",
    "MaskPaint",
    "MaskStop",
    "MaskSurface",
    "NpRng",
    "Num",
    "P",
    "Paint",
    "Params",
    "Path",
    "PatternSurface",
    "Point",
    "Rect",
    "Ref",
    "Rng",
    "Stop",
    "Style",
    "Vec",
    "by_regime",
    "clamp",
    "design",
    "knob",
    "ladder",
    "lerp",
    "mix",
    "polar",
    "ramp",
    "smoothstep",
]
