"""The core design API; the helpers live in walldye.geom, walldye.field and walldye.pixel."""

from ._cache import cached
from ._canvas import Canvas
from ._color import (
    ACCENT,
    ACCENT_1,
    ACCENT_2,
    ACCENT_3,
    ACCENT_4,
    ACCENT_5,
    ACCENT_6,
    ACCENT_7,
    ACCENT_8,
    ACCENT_HI,
    BG,
    BG_ALT,
    BG_DEEP,
    BLACK,
    FG,
    FG_ALT,
    MASK_BLACK,
    MASK_WHITE,
    MUTED,
    UI,
    UI_ALT,
    UI_HI,
    Color,
    Ladder,
    MaskColor,
    by_regime,
    ladder,
    mix,
    ramp,
)
from ._design import design
from ._params import Params, knob
from ._path import P, Path
from ._surfaces import Buckets, ClipSurface, MaskSurface, PatternSurface
from ._svg import (
    FillRule,
    LineCap,
    LineJoin,
    MaskPaint,
    MaskStop,
    NpRng,
    Paint,
    Ref,
    Rng,
    Stop,
    Style,
)
from ._vec import Num, Point, Rect, Vec, clamp, lerp, polar, smoothstep

__all__ = [
    "ACCENT",
    "ACCENT_1",
    "ACCENT_2",
    "ACCENT_3",
    "ACCENT_4",
    "ACCENT_5",
    "ACCENT_6",
    "ACCENT_7",
    "ACCENT_8",
    "ACCENT_HI",
    "BG",
    "BG_ALT",
    "BG_DEEP",
    "BLACK",
    "FG",
    "FG_ALT",
    "MASK_BLACK",
    "MASK_WHITE",
    "MUTED",
    "UI",
    "UI_ALT",
    "UI_HI",
    "Buckets",
    "Canvas",
    "ClipSurface",
    "Color",
    "FillRule",
    "Ladder",
    "LineCap",
    "LineJoin",
    "MaskColor",
    "MaskPaint",
    "MaskStop",
    "MaskSurface",
    "NpRng",
    "Num",
    "P",
    "Paint",
    "Params",
    "Path",
    "PatternSurface",
    "Point",
    "Rect",
    "Ref",
    "Rng",
    "Stop",
    "Style",
    "Vec",
    "by_regime",
    "cached",
    "clamp",
    "design",
    "knob",
    "ladder",
    "lerp",
    "mix",
    "polar",
    "ramp",
    "smoothstep",
]
